import Head from 'next/head';

import { getLayout } from '@/components/layout/Layout';
import { useTranslation } from '@/shared/hooks/useTranslation';

function Home() {
    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>{t.auth.privacyPolicyPage.h1}</h1>
        </>
    );
}

Home.getLayout = getLayout;
export default Home;
