import Head from 'next/head';

import { getLayout } from '@/components/layout/Layout';

function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>MAIN</h1>
        </>
    );
}

Home.getLayout = getLayout;
export default Home;
